name: example
description: Pull-Down button example

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  pull_down_button:
    path: ../

dev_dependencies:
  very_good_analysis: ^4.0.0+1