name: pull_down_button
description: A package that implements Pull-Down Button from iOS 14 in Flutter. Highly customizable.
version: 0.10.1
homepage: https://github.com/notDmDrl/pull_down_button
repository: https://github.com/notDmDrl/pull_down_button
issue_tracker: https://github.com/notDmDrl/pull_down_button/issues

screenshots:
  - description: 'Pull-Down Menu in default light theme'
    path: readme_content/usage.png
  - description: 'Pull-Down Menu in default dark theme'
    path: readme_content/usage_dark.png

topics:
  - cupertino
  - menu

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0

dev_dependencies:
  very_good_analysis: ^6.0.0
